// Copyright (c) 2023 Admenri. All rights reserved.
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=9d593f2bd3c349649a1851ef487f523829f150d2$
//

#ifndef ACF_INCLUDE_CAPI_ACF_CALLBACK_CAPI_H_
#define ACF_INCLUDE_CAPI_ACF_CALLBACK_CAPI_H_
#pragma once

#include "include/capi/acf_base_capi.h"
#include "include/internal/acf_scoped_refptr.h"

#ifdef __cplusplus
extern "C" {
#endif

///
/// Complete event notify
///
typedef struct _acf_complete_handler_t {
  ///
  /// Base structure.
  ///
  acf_base_ref_counted_t base;

  ///
  /// Called when task has been completed.
  ///
  void(ACF_CALLBACK* on_complete)(struct _acf_complete_handler_t* self);
} acf_complete_handler_t;

#ifdef __cplusplus
}
#endif

#endif  // ACF_INCLUDE_CAPI_ACF_CALLBACK_CAPI_H_
