// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e9d208a4aeb657e5fb62f5ba59ad8f8345fc129c$
//

// Define used to facilitate parsing.
#define ACF_GLOBAL
