// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=11cee37a5500cd1655337a0a49448447c03fa1e7$
//

#ifndef ACF_CTOCPP_BROWSER_CTOCPP_H_
#define ACF_CTOCPP_BROWSER_CTOCPP_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_environment.h"
#include "include/acf_profile.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfBrowserCToCpp
    : public AcfCToCppRefCounted<AcfBrowserCToCpp, AcfBrowser, acf_browser_t> {
 public:
  AcfBrowserCToCpp();
  virtual ~AcfBrowserCToCpp();

  // AcfBrowser methods.
  bool IsSame(AcfRefPtr<AcfBrowser> that) override;
  AcfRefPtr<AcfBrowserHandler> GetHandler() override;
  AcfUserData GetUserData() override;
  AcfRefPtr<AcfEnvironment> GetEnvironment() override;
  void Close(bool force) override;
  AcfWindowHandle GetWindowHandle() override;
  bool IsValid() override;
  bool CanGoBack() override;
  bool CanGoForward() override;
  void GoBack() override;
  void GoForward() override;
  void Reload(bool ignore_cache) override;
  void Stop() override;
  bool IsLoading() override;
  void LoadURL(const AcfString& url) override;
  AcfString GetURL() override;
  AcfString GetTitle() override;
  void Focus() override;
  void SetVisible(bool visible) override;
  bool GetVisible() override;
  AcfRefPtr<AcfProfile> GetProfile() override;
};

#endif  // ACF_CTOCPP_BROWSER_CTOCPP_H_
