// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=267e403e5b8ea92773b2c32eedd7d9af688eedf3$
//

#include "libacf_dll/ctocpp/complete_handler_ctocpp.h"

// VIRTUAL METHODS - Body may be edited by hand.

void AcfCompleteHandlerCToCpp::OnComplete() {
  acf_complete_handler_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, on_complete))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->on_complete(_struct);
}

// CONSTRUCTOR - Do not edit by hand.

AcfCompleteHandlerCToCpp::AcfCompleteHandlerCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

AcfCompleteHandlerCToCpp::~AcfCompleteHandlerCToCpp() {}

template <>
acf_complete_handler_t* AcfCToCppRefCounted<
    AcfCompleteHandlerCToCpp,
    AcfCompleteHandler,
    acf_complete_handler_t>::UnwrapDerived(AcfWrapperType type,
                                           AcfCompleteHandler* c) {
  return nullptr;
}

template <>
AcfWrapperType AcfCToCppRefCounted<AcfCompleteHandlerCToCpp,
                                   AcfCompleteHandler,
                                   acf_complete_handler_t>::kWrapperType =
    WT_COMPLETE_HANDLER;
