// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=50dbcd345dc9c7894a67996ac54acea625a84bb9$
//

#ifndef ACF_CTOCPP_COMPLETE_VALUE_HANDLER_CTOCPP_H_
#define ACF_CTOCPP_COMPLETE_VALUE_HANDLER_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class AcfCompleteValueHandlerCToCpp
    : public AcfCToCppRefCounted<AcfCompleteValueHandlerCToCpp,
                                 AcfCompleteValueHandler,
                                 acf_complete_value_handler_t> {
 public:
  AcfCompleteValueHandlerCToCpp();
  virtual ~AcfCompleteValueHandlerCToCpp();

  // AcfCompleteValueHandler methods.
  void OnComplete(AcfRefPtr<AcfValue> value) override;
};

#endif  // ACF_CTOCPP_COMPLETE_VALUE_HANDLER_CTOCPP_H_
