// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=005b4c0589001e867df86cf3191beed0b2f6f8b1$
//

#ifndef ACF_CTOCPP_COMPLETE_HANDLER_CTOCPP_H_
#define ACF_CTOCPP_COMPLETE_HANDLER_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/capi/acf_callback_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class AcfCompleteHandlerCToCpp
    : public AcfCToCppRefCounted<AcfCompleteHandlerCToCpp,
                                 AcfCompleteHandler,
                                 acf_complete_handler_t> {
 public:
  AcfCompleteHandlerCToCpp();
  virtual ~AcfCompleteHandlerCToCpp();

  // AcfCompleteHandler methods.
  void OnComplete() override;
};

#endif  // ACF_CTOCPP_COMPLETE_HANDLER_CTOCPP_H_
