// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c082c93ceec20ee2a29930be4c1b48a50a6609a4$
//

#include "libacf_dll/ctocpp/context_menu_params_ctocpp.h"

// VIRTUAL METHODS - Body may be edited by hand.

int AcfContextMenuParamsCToCpp::GetXCoord() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_xcoord))
    return 0;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_xcoord(_struct);

  // Return type: simple
  return _retval;
}

int AcfContextMenuParamsCToCpp::GetYCoord() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_ycoord))
    return 0;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_ycoord(_struct);

  // Return type: simple
  return _retval;
}

AcfContextMenuParams::TypeFlags AcfContextMenuParamsCToCpp::GetTypeFlags() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_type_flags))
    return CM_TYPEFLAG_NONE;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_context_menu_type_flags_t _retval = _struct->get_type_flags(_struct);

  // Return type: simple
  return _retval;
}

AcfString AcfContextMenuParamsCToCpp::GetLinkUrl() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_link_url))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_link_url(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

AcfString AcfContextMenuParamsCToCpp::GetUnfilteredLinkUrl() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_unfiltered_link_url))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_unfiltered_link_url(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

AcfString AcfContextMenuParamsCToCpp::GetSourceUrl() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_source_url))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_source_url(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

AcfString AcfContextMenuParamsCToCpp::GetPageUrl() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_page_url))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_page_url(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

AcfString AcfContextMenuParamsCToCpp::GetFrameUrl() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_frame_url))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_frame_url(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

AcfString AcfContextMenuParamsCToCpp::GetFrameCharset() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_frame_charset))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_frame_charset(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

AcfContextMenuParams::MediaType AcfContextMenuParamsCToCpp::GetMediaType() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_media_type))
    return CM_MEDIATYPE_NONE;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_context_menu_media_type_t _retval = _struct->get_media_type(_struct);

  // Return type: simple
  return _retval;
}

AcfContextMenuParams::MediaStateFlags
AcfContextMenuParamsCToCpp::GetMediaStateFlags() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_media_state_flags))
    return CM_MEDIAFLAG_NONE;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_context_menu_media_state_flags_t _retval =
      _struct->get_media_state_flags(_struct);

  // Return type: simple
  return _retval;
}

AcfString AcfContextMenuParamsCToCpp::GetSelectionText() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_selection_text))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_selection_text(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

bool AcfContextMenuParamsCToCpp::IsEditable() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, is_editable))
    return false;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_editable(_struct);

  // Return type: bool
  return _retval ? true : false;
}

AcfContextMenuParams::EditStateFlags
AcfContextMenuParamsCToCpp::GetEditStateFlags() {
  acf_context_menu_params_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_edit_state_flags))
    return CM_EDITFLAG_NONE;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_context_menu_edit_state_flags_t _retval =
      _struct->get_edit_state_flags(_struct);

  // Return type: simple
  return _retval;
}

// CONSTRUCTOR - Do not edit by hand.

AcfContextMenuParamsCToCpp::AcfContextMenuParamsCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

AcfContextMenuParamsCToCpp::~AcfContextMenuParamsCToCpp() {}

template <>
acf_context_menu_params_t* AcfCToCppRefCounted<
    AcfContextMenuParamsCToCpp,
    AcfContextMenuParams,
    acf_context_menu_params_t>::UnwrapDerived(AcfWrapperType type,
                                              AcfContextMenuParams* c) {
  return nullptr;
}

template <>
AcfWrapperType AcfCToCppRefCounted<AcfContextMenuParamsCToCpp,
                                   AcfContextMenuParams,
                                   acf_context_menu_params_t>::kWrapperType =
    WT_CONTEXT_MENU_PARAMS;
