// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=8c36e47b1cd9be8951eddb5a1388459abaa88a97$
//

#include "libacf_dll/ctocpp/context_menu_callback_ctocpp.h"

// VIRTUAL METHODS - Body may be edited by hand.

void AcfContextMenuCallbackCToCpp::Continue(bool suppress) {
  acf_context_menu_callback_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, cont))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->cont(_struct, suppress);
}

// CONSTRUCTOR - Do not edit by hand.

AcfContextMenuCallbackCToCpp::AcfContextMenuCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

AcfContextMenuCallbackCToCpp::~AcfContextMenuCallbackCToCpp() {}

template <>
acf_context_menu_callback_t* AcfCToCppRefCounted<
    AcfContextMenuCallbackCToCpp,
    AcfContextMenuCallback,
    acf_context_menu_callback_t>::UnwrapDerived(AcfWrapperType type,
                                                AcfContextMenuCallback* c) {
  return nullptr;
}

template <>
AcfWrapperType AcfCToCppRefCounted<AcfContextMenuCallbackCToCpp,
                                   AcfContextMenuCallback,
                                   acf_context_menu_callback_t>::kWrapperType =
    WT_CONTEXT_MENU_CALLBACK;
