// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=1488732ddef71d4c3084211fa4800d68b51982f6$
//

#ifndef ACF_CTOCPP_COOKIE_VISITOR_CTOCPP_H_
#define ACF_CTOCPP_COOKIE_VISITOR_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_environment.h"
#include "include/acf_profile.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class AcfCookieVisitorCToCpp
    : public AcfCToCppRefCounted<AcfCookieVisitorCToCpp,
                                 AcfCookieVisitor,
                                 acf_cookie_visitor_t> {
 public:
  AcfCookieVisitorCToCpp();
  virtual ~AcfCookieVisitorCToCpp();

  // AcfCookieVisitor methods.
  void Visit(AcfRefPtr<AcfCookiesGetter> cookie_getter) override;
};

#endif  // ACF_CTOCPP_COOKIE_VISITOR_CTOCPP_H_
