// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=a541eba913a0db21acae0a02e3fbf029467c5727$
//

#ifndef ACF_CTOCPP_COOKIE_CTOCPP_H_
#define ACF_CTOCPP_COOKIE_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_environment.h"
#include "include/acf_profile.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfCookieCToCpp
    : public AcfCToCppRefCounted<AcfCookieCToCpp, AcfCookie, acf_cookie_t> {
 public:
  AcfCookieCToCpp();
  virtual ~AcfCookieCToCpp();

  // AcfCookie methods.
  AcfString GetName() override;
  void SetName(const AcfString& value) override;
  AcfString GetValue() override;
  void SetValue(const AcfString& value) override;
  AcfString GetDomain() override;
  void SetDomain(const AcfString& value) override;
  AcfString GetPath() override;
  void SetPath(const AcfString& value) override;
  bool IsHttponly() override;
  void SetHttponly(bool value) override;
  bool IsSecure() override;
  void SetSecure(bool value) override;
  AcfCookieSameSite GetSameSite() override;
  void SetSameSite(AcfCookieSameSite value) override;
  AcfCookiePriority GetPriority() override;
  void SetPriority(AcfCookiePriority value) override;
  double GetCreation() override;
  void SetCreation(double value) override;
  double GetExpiry() override;
  void SetExpiry(double value) override;
  double GetLastAccess() override;
  void SetLastAccess(double value) override;
  double GetLastUpdate() override;
  void SetLastUpdate(double value) override;
};

#endif  // ACF_CTOCPP_COOKIE_CTOCPP_H_
