// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=a3d9e7969fab2a4a70480cd906cd0cfc42e029f3$
//

#ifndef ACF_CTOCPP_COOKIES_GETTER_CTOCPP_H_
#define ACF_CTOCPP_COOKIES_GETTER_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_environment.h"
#include "include/acf_profile.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfCookiesGetterCToCpp
    : public AcfCToCppRefCounted<AcfCookiesGetterCToCpp,
                                 AcfCookiesGetter,
                                 acf_cookies_getter_t> {
 public:
  AcfCookiesGetterCToCpp();
  virtual ~AcfCookiesGetterCToCpp();

  // AcfCookiesGetter methods.
  size_t GetCookiesCount() override;
  AcfRefPtr<AcfCookie> GetCookieAt(size_t index) override;
};

#endif  // ACF_CTOCPP_COOKIES_GETTER_CTOCPP_H_
