// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=982e8f95aaf24cc7006c0db012c0436f7ff7f119$
//

#ifndef ACF_CTOCPP_DICTIONARY_VALUE_CTOCPP_H_
#define ACF_CTOCPP_DICTIONARY_VALUE_CTOCPP_H_
#pragma once

#include "include/acf_values.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfDictionaryValueCToCpp
    : public AcfCToCppRefCounted<AcfDictionaryValueCToCpp,
                                 AcfDictionaryValue,
                                 acf_dictionary_value_t> {
 public:
  AcfDictionaryValueCToCpp();
  virtual ~AcfDictionaryValueCToCpp();

  // AcfDictionaryValue methods.
  bool IsValid() override;
  bool IsOwned() override;
  bool IsReadOnly() override;
  bool IsSame(AcfRefPtr<AcfDictionaryValue> that) override;
  bool IsEqual(AcfRefPtr<AcfDictionaryValue> that) override;
  AcfRefPtr<AcfDictionaryValue> Copy(bool exclude_empty_children) override;
  size_t GetSize() override;
  bool Clear() override;
  bool HasKey(const AcfString& key) override;
  bool GetKeys(KeyList& keys) override;
  bool Remove(const AcfString& key) override;
  AcfValueType GetType(const AcfString& key) override;
  AcfRefPtr<AcfValue> GetValue(const AcfString& key) override;
  bool GetBool(const AcfString& key) override;
  int GetInt(const AcfString& key) override;
  double GetDouble(const AcfString& key) override;
  AcfString GetString(const AcfString& key) override;
  AcfRefPtr<AcfBinaryValue> GetBinary(const AcfString& key) override;
  AcfRefPtr<AcfDictionaryValue> GetDictionary(const AcfString& key) override;
  AcfRefPtr<AcfListValue> GetList(const AcfString& key) override;
  bool SetValue(const AcfString& key, AcfRefPtr<AcfValue> value) override;
  bool SetNull(const AcfString& key) override;
  bool SetBool(const AcfString& key, bool value) override;
  bool SetInt(const AcfString& key, int value) override;
  bool SetDouble(const AcfString& key, double value) override;
  bool SetString(const AcfString& key, const AcfString& value) override;
  bool SetBinary(const AcfString& key,
                 AcfRefPtr<AcfBinaryValue> value) override;
  bool SetDictionary(const AcfString& key,
                     AcfRefPtr<AcfDictionaryValue> value) override;
  bool SetList(const AcfString& key, AcfRefPtr<AcfListValue> value) override;
};

#endif  // ACF_CTOCPP_DICTIONARY_VALUE_CTOCPP_H_
