// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=320968e24ec0d27bb79bc196825ddafae72bb4b4$
//

#include "libacf_dll/ctocpp/frame_ctocpp.h"
#include "libacf_dll/ctocpp/browser_ctocpp.h"

// VIRTUAL METHODS - Body may be edited by hand.

bool AcfFrameCToCpp::IsValid() {
  acf_frame_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, is_valid))
    return false;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_valid(_struct);

  // Return type: bool
  return _retval ? true : false;
}

bool AcfFrameCToCpp::IsSame(AcfRefPtr<AcfFrame> object) {
  acf_frame_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, is_same))
    return false;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: object; type: refptr_same
  if (!object.get())
    return false;

  // Execute
  int _retval = _struct->is_same(_struct, AcfFrameCToCpp::Unwrap(object));

  // Return type: bool
  return _retval ? true : false;
}

AcfRefPtr<AcfFrame> AcfFrameCToCpp::GetParent() {
  acf_frame_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_parent))
    return nullptr;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_frame_t* _retval = _struct->get_parent(_struct);

  // Return type: refptr_same
  return AcfFrameCToCpp::Wrap(_retval);
}

AcfRefPtr<AcfBrowser> AcfFrameCToCpp::GetBrowser() {
  acf_frame_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_browser))
    return nullptr;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_browser_t* _retval = _struct->get_browser(_struct);

  // Return type: refptr_same
  return AcfBrowserCToCpp::Wrap(_retval);
}

AcfString AcfFrameCToCpp::GetURL() {
  acf_frame_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_url))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_url(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

AcfString AcfFrameCToCpp::GetName() {
  acf_frame_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_name))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_name(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

int64 AcfFrameCToCpp::GetIdentifier() {
  acf_frame_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_identifier))
    return 0;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int64 _retval = _struct->get_identifier(_struct);

  // Return type: simple
  return _retval;
}

bool AcfFrameCToCpp::IsMain() {
  acf_frame_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, is_main))
    return false;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_main(_struct);

  // Return type: bool
  return _retval ? true : false;
}

// CONSTRUCTOR - Do not edit by hand.

AcfFrameCToCpp::AcfFrameCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

AcfFrameCToCpp::~AcfFrameCToCpp() {}

template <>
acf_frame_t*
AcfCToCppRefCounted<AcfFrameCToCpp, AcfFrame, acf_frame_t>::UnwrapDerived(
    AcfWrapperType type,
    AcfFrame* c) {
  return nullptr;
}

template <>
AcfWrapperType
    AcfCToCppRefCounted<AcfFrameCToCpp, AcfFrame, acf_frame_t>::kWrapperType =
        WT_FRAME;
