// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b01d217b0f1b05e418d889176da72c465f260f47$
//

#ifndef ACF_CTOCPP_LIST_VALUE_CTOCPP_H_
#define ACF_CTOCPP_LIST_VALUE_CTOCPP_H_
#pragma once

#include "include/acf_values.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfListValueCToCpp : public AcfCToCppRefCounted<AcfListValueCToCpp,
                                                      AcfListValue,
                                                      acf_list_value_t> {
 public:
  AcfListValueCToCpp();
  virtual ~AcfListValueCToCpp();

  // AcfListValue methods.
  bool IsValid() override;
  bool IsOwned() override;
  bool IsReadOnly() override;
  bool IsSame(AcfRefPtr<AcfListValue> that) override;
  bool IsEqual(AcfRefPtr<AcfListValue> that) override;
  AcfRefPtr<AcfListValue> Copy() override;
  bool SetSize(size_t size) override;
  size_t GetSize() override;
  bool Clear() override;
  bool Remove(size_t index) override;
  AcfValueType GetType(size_t index) override;
  AcfRefPtr<AcfValue> GetValue(size_t index) override;
  bool GetBool(size_t index) override;
  int GetInt(size_t index) override;
  double GetDouble(size_t index) override;
  AcfString GetString(size_t index) override;
  AcfRefPtr<AcfBinaryValue> GetBinary(size_t index) override;
  AcfRefPtr<AcfDictionaryValue> GetDictionary(size_t index) override;
  AcfRefPtr<AcfListValue> GetList(size_t index) override;
  bool SetValue(size_t index, AcfRefPtr<AcfValue> value) override;
  bool SetNull(size_t index) override;
  bool SetBool(size_t index, bool value) override;
  bool SetInt(size_t index, int value) override;
  bool SetDouble(size_t index, double value) override;
  bool SetString(size_t index, const AcfString& value) override;
  bool SetBinary(size_t index, AcfRefPtr<AcfBinaryValue> value) override;
  bool SetDictionary(size_t index,
                     AcfRefPtr<AcfDictionaryValue> value) override;
  bool SetList(size_t index, AcfRefPtr<AcfListValue> value) override;
};

#endif  // ACF_CTOCPP_LIST_VALUE_CTOCPP_H_
