// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e036d0ac3191680a23b2fe98aa9400b6c6c18841$
//

#ifndef ACF_CTOCPP_NUMBER_COMPLETE_HANDLER_CTOCPP_H_
#define ACF_CTOCPP_NUMBER_COMPLETE_HANDLER_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class AcfNumberCompleteHandlerCToCpp
    : public AcfCToCppRefCounted<AcfNumberCompleteHandlerCToCpp,
                                 AcfNumberCompleteHandler,
                                 acf_number_complete_handler_t> {
 public:
  AcfNumberCompleteHandlerCToCpp();
  virtual ~AcfNumberCompleteHandlerCToCpp();

  // AcfNumberCompleteHandler methods.
  void OnComplete(int value) override;
};

#endif  // ACF_CTOCPP_NUMBER_COMPLETE_HANDLER_CTOCPP_H_
