// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=160f284e01be750fbeefe952353bddbe5b39986c$
//

#include "libacf_dll/ctocpp/number_complete_handler_ctocpp.h"

// VIRTUAL METHODS - Body may be edited by hand.

void AcfNumberCompleteHandlerCToCpp::OnComplete(int value) {
  acf_number_complete_handler_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, on_complete))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->on_complete(_struct, value);
}

// CONSTRUCTOR - Do not edit by hand.

AcfNumberCompleteHandlerCToCpp::AcfNumberCompleteHandlerCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

AcfNumberCompleteHandlerCToCpp::~AcfNumberCompleteHandlerCToCpp() {}

template <>
acf_number_complete_handler_t* AcfCToCppRefCounted<
    AcfNumberCompleteHandlerCToCpp,
    AcfNumberCompleteHandler,
    acf_number_complete_handler_t>::UnwrapDerived(AcfWrapperType type,
                                                  AcfNumberCompleteHandler* c) {
  return nullptr;
}

template <>
AcfWrapperType
    AcfCToCppRefCounted<AcfNumberCompleteHandlerCToCpp,
                        AcfNumberCompleteHandler,
                        acf_number_complete_handler_t>::kWrapperType =
        WT_NUMBER_COMPLETE_HANDLER;
