// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=3169c4ab5ecb6c0c3a64efeb2a44c802fa55b7b0$
//

#include "libacf_dll/ctocpp/profile_ctocpp.h"
#include "libacf_dll/cpptoc/complete_handler_cpptoc.h"
#include "libacf_dll/cpptoc/profile_handler_cpptoc.h"

// VIRTUAL METHODS - Body may be edited by hand.

AcfRefPtr<AcfProfileHandler> AcfProfileCToCpp::GetHandler() {
  acf_profile_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_handler))
    return nullptr;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_profile_handler_t* _retval = _struct->get_handler(_struct);

  // Return type: refptr_diff
  return AcfProfileHandlerCppToC::Unwrap(_retval);
}

bool AcfProfileCToCpp::IsValid() {
  acf_profile_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, is_valid))
    return false;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_valid(_struct);

  // Return type: bool
  return _retval ? true : false;
}

AcfString AcfProfileCToCpp::GetPath() {
  acf_profile_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_path))
    return AcfString();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  acf_string_userfree_t _retval = _struct->get_path(_struct);

  // Return type: string
  AcfString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

void AcfProfileCToCpp::RemoveBrowsingData(
    RemoveDataType data_type,
    bool no_checks,
    AcfRefPtr<AcfCompleteHandler> handler) {
  acf_profile_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, remove_browsing_data))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: handler

  // Execute
  _struct->remove_browsing_data(_struct, data_type, no_checks,
                                AcfCompleteHandlerCppToC::Wrap(handler));
}

// CONSTRUCTOR - Do not edit by hand.

AcfProfileCToCpp::AcfProfileCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

AcfProfileCToCpp::~AcfProfileCToCpp() {}

template <>
acf_profile_t*
AcfCToCppRefCounted<AcfProfileCToCpp, AcfProfile, acf_profile_t>::UnwrapDerived(
    AcfWrapperType type,
    AcfProfile* c) {
  return nullptr;
}

template <>
AcfWrapperType AcfCToCppRefCounted<AcfProfileCToCpp,
                                   AcfProfile,
                                   acf_profile_t>::kWrapperType = WT_PROFILE;
