// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e31e2a640265994402ee62f97418ca4d2d34cb79$
//

#ifndef ACF_CTOCPP_STRING_VISITOR_CTOCPP_H_
#define ACF_CTOCPP_STRING_VISITOR_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class AcfStringVisitorCToCpp
    : public AcfCToCppRefCounted<AcfStringVisitorCToCpp,
                                 AcfStringVisitor,
                                 acf_string_visitor_t> {
 public:
  AcfStringVisitorCToCpp();
  virtual ~AcfStringVisitorCToCpp();

  // AcfStringVisitor methods.
  void Visit(const AcfString& string) override;
};

#endif  // ACF_CTOCPP_STRING_VISITOR_CTOCPP_H_
