// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e6d48beef7d71ca74ba7b005ad498aae6b423bf9$
//

#ifndef ACF_CTOCPP_VALUE_CTOCPP_H_
#define ACF_CTOCPP_VALUE_CTOCPP_H_
#pragma once

#include "include/acf_values.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfValueCToCpp
    : public AcfCToCppRefCounted<AcfValueCToCpp, AcfValue, acf_value_t> {
 public:
  AcfValueCToCpp();
  virtual ~AcfValueCToCpp();

  // AcfValue methods.
  bool IsValid() override;
  bool IsOwned() override;
  bool IsReadOnly() override;
  bool IsSame(AcfRefPtr<AcfValue> that) override;
  bool IsEqual(AcfRefPtr<AcfValue> that) override;
  AcfRefPtr<AcfValue> Copy() override;
  AcfValueType GetType() override;
  bool GetBool() override;
  int GetInt() override;
  double GetDouble() override;
  AcfString GetString() override;
  AcfRefPtr<AcfBinaryValue> GetBinary() override;
  AcfRefPtr<AcfDictionaryValue> GetDictionary() override;
  AcfRefPtr<AcfListValue> GetList() override;
  bool SetNull() override;
  bool SetBool(bool value) override;
  bool SetInt(int value) override;
  bool SetDouble(double value) override;
  bool SetString(const AcfString& value) override;
  bool SetBinary(AcfRefPtr<AcfBinaryValue> value) override;
  bool SetDictionary(AcfRefPtr<AcfDictionaryValue> value) override;
  bool SetList(AcfRefPtr<AcfListValue> value) override;
};

#endif  // ACF_CTOCPP_VALUE_CTOCPP_H_
