// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=81a3dc8003c3b527c48b66150639a858d03fbc70$
//

#ifndef ACF_CPPTOC_BROWSER_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_BROWSER_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_browser_handler.h"
#include "include/capi/acf_browser_handler_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfBrowserHandlerCppToC
    : public AcfCppToCRefCounted<AcfBrowserHandlerCppToC,
                                 AcfBrowserHandler,
                                 acf_browser_handler_t> {
 public:
  AcfBrowserHandlerCppToC();
  virtual ~AcfBrowserHandlerCppToC();
};

#endif  // ACF_CPPTOC_BROWSER_HANDLER_CPPTOC_H_
