// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e9d6c41910b9c9397f759ad6f8bb564cea772d3e$
//

#ifndef ACF_CPPTOC_COMPLETE_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_COMPLETE_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfCompleteHandlerCppToC
    : public AcfCppToCRefCounted<AcfCompleteHandlerCppToC,
                                 AcfCompleteHandler,
                                 acf_complete_handler_t> {
 public:
  AcfCompleteHandlerCppToC();
  virtual ~AcfCompleteHandlerCppToC();
};

#endif  // ACF_CPPTOC_COMPLETE_HANDLER_CPPTOC_H_
