// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=87e66f7331d02459af0b29345fc34b7ff7fa4293$
//

#include "libacf_dll/cpptoc/context_menu_params_cpptoc.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

int ACF_CALLBACK
context_menu_params_get_xcoord(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return 0;

  // Execute
  int _retval = AcfContextMenuParamsCppToC::Get(self)->GetXCoord();

  // Return type: simple
  return _retval;
}

int ACF_CALLBACK
context_menu_params_get_ycoord(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return 0;

  // Execute
  int _retval = AcfContextMenuParamsCppToC::Get(self)->GetYCoord();

  // Return type: simple
  return _retval;
}

acf_context_menu_type_flags_t ACF_CALLBACK
context_menu_params_get_type_flags(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return CM_TYPEFLAG_NONE;

  // Execute
  acf_context_menu_type_flags_t _retval =
      AcfContextMenuParamsCppToC::Get(self)->GetTypeFlags();

  // Return type: simple
  return _retval;
}

acf_string_userfree_t ACF_CALLBACK
context_menu_params_get_link_url(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return NULL;

  // Execute
  AcfString _retval = AcfContextMenuParamsCppToC::Get(self)->GetLinkUrl();

  // Return type: string
  return _retval.DetachToUserFree();
}

acf_string_userfree_t ACF_CALLBACK context_menu_params_get_unfiltered_link_url(
    struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return NULL;

  // Execute
  AcfString _retval =
      AcfContextMenuParamsCppToC::Get(self)->GetUnfilteredLinkUrl();

  // Return type: string
  return _retval.DetachToUserFree();
}

acf_string_userfree_t ACF_CALLBACK
context_menu_params_get_source_url(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return NULL;

  // Execute
  AcfString _retval = AcfContextMenuParamsCppToC::Get(self)->GetSourceUrl();

  // Return type: string
  return _retval.DetachToUserFree();
}

acf_string_userfree_t ACF_CALLBACK
context_menu_params_get_page_url(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return NULL;

  // Execute
  AcfString _retval = AcfContextMenuParamsCppToC::Get(self)->GetPageUrl();

  // Return type: string
  return _retval.DetachToUserFree();
}

acf_string_userfree_t ACF_CALLBACK
context_menu_params_get_frame_url(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return NULL;

  // Execute
  AcfString _retval = AcfContextMenuParamsCppToC::Get(self)->GetFrameUrl();

  // Return type: string
  return _retval.DetachToUserFree();
}

acf_string_userfree_t ACF_CALLBACK
context_menu_params_get_frame_charset(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return NULL;

  // Execute
  AcfString _retval = AcfContextMenuParamsCppToC::Get(self)->GetFrameCharset();

  // Return type: string
  return _retval.DetachToUserFree();
}

acf_context_menu_media_type_t ACF_CALLBACK
context_menu_params_get_media_type(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return CM_MEDIATYPE_NONE;

  // Execute
  acf_context_menu_media_type_t _retval =
      AcfContextMenuParamsCppToC::Get(self)->GetMediaType();

  // Return type: simple
  return _retval;
}

acf_context_menu_media_state_flags_t ACF_CALLBACK
context_menu_params_get_media_state_flags(
    struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return CM_MEDIAFLAG_NONE;

  // Execute
  acf_context_menu_media_state_flags_t _retval =
      AcfContextMenuParamsCppToC::Get(self)->GetMediaStateFlags();

  // Return type: simple
  return _retval;
}

acf_string_userfree_t ACF_CALLBACK context_menu_params_get_selection_text(
    struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return NULL;

  // Execute
  AcfString _retval = AcfContextMenuParamsCppToC::Get(self)->GetSelectionText();

  // Return type: string
  return _retval.DetachToUserFree();
}

int ACF_CALLBACK
context_menu_params_is_editable(struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return 0;

  // Execute
  bool _retval = AcfContextMenuParamsCppToC::Get(self)->IsEditable();

  // Return type: bool
  return _retval;
}

acf_context_menu_edit_state_flags_t ACF_CALLBACK
context_menu_params_get_edit_state_flags(
    struct _acf_context_menu_params_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return CM_EDITFLAG_NONE;

  // Execute
  acf_context_menu_edit_state_flags_t _retval =
      AcfContextMenuParamsCppToC::Get(self)->GetEditStateFlags();

  // Return type: simple
  return _retval;
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

AcfContextMenuParamsCppToC::AcfContextMenuParamsCppToC() {
  GetStruct()->get_xcoord = context_menu_params_get_xcoord;
  GetStruct()->get_ycoord = context_menu_params_get_ycoord;
  GetStruct()->get_type_flags = context_menu_params_get_type_flags;
  GetStruct()->get_link_url = context_menu_params_get_link_url;
  GetStruct()->get_unfiltered_link_url =
      context_menu_params_get_unfiltered_link_url;
  GetStruct()->get_source_url = context_menu_params_get_source_url;
  GetStruct()->get_page_url = context_menu_params_get_page_url;
  GetStruct()->get_frame_url = context_menu_params_get_frame_url;
  GetStruct()->get_frame_charset = context_menu_params_get_frame_charset;
  GetStruct()->get_media_type = context_menu_params_get_media_type;
  GetStruct()->get_media_state_flags =
      context_menu_params_get_media_state_flags;
  GetStruct()->get_selection_text = context_menu_params_get_selection_text;
  GetStruct()->is_editable = context_menu_params_is_editable;
  GetStruct()->get_edit_state_flags = context_menu_params_get_edit_state_flags;
}

// DESTRUCTOR - Do not edit by hand.

AcfContextMenuParamsCppToC::~AcfContextMenuParamsCppToC() {}

template <>
AcfRefPtr<AcfContextMenuParams> AcfCppToCRefCounted<
    AcfContextMenuParamsCppToC,
    AcfContextMenuParams,
    acf_context_menu_params_t>::UnwrapDerived(AcfWrapperType type,
                                              acf_context_menu_params_t* s) {
  return nullptr;
}

template <>
AcfWrapperType AcfCppToCRefCounted<AcfContextMenuParamsCppToC,
                                   AcfContextMenuParams,
                                   acf_context_menu_params_t>::kWrapperType =
    WT_CONTEXT_MENU_PARAMS;
