// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c5a8aaba18b2a2c1af797c47a5a804c4da25551c$
//

#ifndef ACF_CPPTOC_CONTEXT_MENU_MODEL_CPPTOC_H_
#define ACF_CPPTOC_CONTEXT_MENU_MODEL_CPPTOC_H_
#pragma once

#include "include/acf_context_menu.h"
#include "include/capi/acf_context_menu_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfContextMenuModelCppToC
    : public AcfCppToCRefCounted<AcfContextMenuModelCppToC,
                                 AcfContextMenuModel,
                                 acf_context_menu_model_t> {
 public:
  AcfContextMenuModelCppToC();
  virtual ~AcfContextMenuModelCppToC();
};

#endif  // ACF_CPPTOC_CONTEXT_MENU_MODEL_CPPTOC_H_
