// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=21a2a22afd2f81be8baff9ac48aa4d599e598d71$
//

#ifndef ACF_CPPTOC_COOKIES_GETTER_CPPTOC_H_
#define ACF_CPPTOC_COOKIES_GETTER_CPPTOC_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_environment.h"
#include "include/acf_profile.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfCookiesGetterCppToC
    : public AcfCppToCRefCounted<AcfCookiesGetterCppToC,
                                 AcfCookiesGetter,
                                 acf_cookies_getter_t> {
 public:
  AcfCookiesGetterCppToC();
  virtual ~AcfCookiesGetterCppToC();
};

#endif  // ACF_CPPTOC_COOKIES_GETTER_CPPTOC_H_
