// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=66c27d91e4b89e43d4d33aee9eaef276f2d85e84$
//

#ifndef ACF_CPPTOC_COOKIE_MANAGER_CPPTOC_H_
#define ACF_CPPTOC_COOKIE_MANAGER_CPPTOC_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_environment.h"
#include "include/acf_profile.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfCookieManagerCppToC
    : public AcfCppToCRefCounted<AcfCookieManagerCppToC,
                                 AcfCookieManager,
                                 acf_cookie_manager_t> {
 public:
  AcfCookieManagerCppToC();
  virtual ~AcfCookieManagerCppToC();
};

#endif  // ACF_CPPTOC_COOKIE_MANAGER_CPPTOC_H_
