// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=11d553a18f15bbb4088c648d7fd8667be2b65e15$
//

#ifndef ACF_CPPTOC_DICTIONARY_VALUE_CPPTOC_H_
#define ACF_CPPTOC_DICTIONARY_VALUE_CPPTOC_H_
#pragma once

#include "include/acf_values.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfDictionaryValueCppToC
    : public AcfCppToCRefCounted<AcfDictionaryValueCppToC,
                                 AcfDictionaryValue,
                                 acf_dictionary_value_t> {
 public:
  AcfDictionaryValueCppToC();
  virtual ~AcfDictionaryValueCppToC();
};

#endif  // ACF_CPPTOC_DICTIONARY_VALUE_CPPTOC_H_
