// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e8bcd09a7f991313efc72c496c96ce92f90b7790$
//

#include "libacf_dll/cpptoc/environment_handler_cpptoc.h"
#include "libacf_dll/ctocpp/environment_ctocpp.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void ACF_CALLBACK environment_handler_on_environment_initialized(
    struct _acf_environment_handler_t* self,
    struct _acf_environment_t* env) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return;
  // Verify param: env; type: refptr_diff
  if (!env)
    return;

  // Execute
  AcfEnvironmentHandlerCppToC::Get(self)->OnEnvironmentInitialized(
      AcfEnvironmentCToCpp::Wrap(env));
}

void ACF_CALLBACK environment_handler_on_environment_destroyed(
    struct _acf_environment_handler_t* self,
    struct _acf_environment_t* env) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return;
  // Verify param: env; type: refptr_diff
  if (!env)
    return;

  // Execute
  AcfEnvironmentHandlerCppToC::Get(self)->OnEnvironmentDestroyed(
      AcfEnvironmentCToCpp::Wrap(env));
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

AcfEnvironmentHandlerCppToC::AcfEnvironmentHandlerCppToC() {
  GetStruct()->on_environment_initialized =
      environment_handler_on_environment_initialized;
  GetStruct()->on_environment_destroyed =
      environment_handler_on_environment_destroyed;
}

// DESTRUCTOR - Do not edit by hand.

AcfEnvironmentHandlerCppToC::~AcfEnvironmentHandlerCppToC() {}

template <>
AcfRefPtr<AcfEnvironmentHandler> AcfCppToCRefCounted<
    AcfEnvironmentHandlerCppToC,
    AcfEnvironmentHandler,
    acf_environment_handler_t>::UnwrapDerived(AcfWrapperType type,
                                              acf_environment_handler_t* s) {
  return nullptr;
}

template <>
AcfWrapperType AcfCppToCRefCounted<AcfEnvironmentHandlerCppToC,
                                   AcfEnvironmentHandler,
                                   acf_environment_handler_t>::kWrapperType =
    WT_ENVIRONMENT_HANDLER;
