// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c0112be1e00cfab9b5de203772675810d084298d$
//

#ifndef ACF_CPPTOC_ENVIRONMENT_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_ENVIRONMENT_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_environment.h"
#include "include/acf_profile.h"
#include "include/acf_values.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfEnvironmentHandlerCppToC
    : public AcfCppToCRefCounted<AcfEnvironmentHandlerCppToC,
                                 AcfEnvironmentHandler,
                                 acf_environment_handler_t> {
 public:
  AcfEnvironmentHandlerCppToC();
  virtual ~AcfEnvironmentHandlerCppToC();
};

#endif  // ACF_CPPTOC_ENVIRONMENT_HANDLER_CPPTOC_H_
