// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=7dce10d2363120569838311c7685d081e5ae1d56$
//

#ifndef ACF_CPPTOC_FRAME_CPPTOC_H_
#define ACF_CPPTOC_FRAME_CPPTOC_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_callback.h"
#include "include/acf_frame.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfFrameCppToC
    : public AcfCppToCRefCounted<AcfFrameCppToC, AcfFrame, acf_frame_t> {
 public:
  AcfFrameCppToC();
  virtual ~AcfFrameCppToC();
};

#endif  // ACF_CPPTOC_FRAME_CPPTOC_H_
