// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f3c0081fe1a90939e5822bcf643e7f009884cffa$
//

#ifndef ACF_CPPTOC_NUMBER_COMPLETE_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_NUMBER_COMPLETE_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfNumberCompleteHandlerCppToC
    : public AcfCppToCRefCounted<AcfNumberCompleteHandlerCppToC,
                                 AcfNumberCompleteHandler,
                                 acf_number_complete_handler_t> {
 public:
  AcfNumberCompleteHandlerCppToC();
  virtual ~AcfNumberCompleteHandlerCppToC();
};

#endif  // ACF_CPPTOC_NUMBER_COMPLETE_HANDLER_CPPTOC_H_
