// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=0a67f1a2d6f449cb2df97b8930f126c172c1e492$
//

#ifndef ACF_CPPTOC_PROFILE_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_PROFILE_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_profile.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfProfileHandlerCppToC
    : public AcfCppToCRefCounted<AcfProfileHandlerCppToC,
                                 AcfProfileHandler,
                                 acf_profile_handler_t> {
 public:
  AcfProfileHandlerCppToC();
  virtual ~AcfProfileHandlerCppToC();
};

#endif  // ACF_CPPTOC_PROFILE_HANDLER_CPPTOC_H_
