// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b2d5933203bffb170059487590bee71493b58029$
//

#ifndef ACF_CPPTOC_VALUE_CPPTOC_H_
#define ACF_CPPTOC_VALUE_CPPTOC_H_
#pragma once

#include "include/acf_values.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfValueCppToC
    : public AcfCppToCRefCounted<AcfValueCppToC, AcfValue, acf_value_t> {
 public:
  AcfValueCppToC();
  virtual ~AcfValueCppToC();
};

#endif  // ACF_CPPTOC_VALUE_CPPTOC_H_
