// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=057f542bc77ee22c77b23fccd094bb58ea1d70ee$
//

#ifndef ACF_WRAPPER_TYPES_H_
#define ACF_WRAPPER_TYPES_H_
#pragma once

enum AcfWrapperType {
  WT_BASE_REF_COUNTED = 1,
  WT_BASE_SCOPED,
  WT_BROWSER,
  WT_BROWSER_HANDLER,
  WT_ENVIRONMENT,
  WT_ENVIRONMENT_HANDLER,
  WT_NEW_WINDOW_DELEGATE,
  WT_PROFILE,
  WT_PROFILE_HANDLER,

  WT_LAST
};

#endif  // ACF_WRAPPER_TYPES_H_
